### PR TITLE
bump to 1.7.0

### PR DESCRIPTION
**Pull request by stilley2**

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by jakirkham** [comment]
Please feel free to reach out for help if you are struggling with CI issues. Chance are if there is a problem you are not alone and someone may have already fixed. The re-rendering above should fix the AppVeyor issue. Please let us know if there are other issues. :)

**Comment by stilley2** [comment]
Thanks for the help @jakirkham!

**Comment by jakirkham** [comment]
Of course. :)

**Pull request merged**
